# Makefile; see License.txt for copyright and terms of use

# Makefile for delta/test/multidelta0.
# Scott McPeak smcpeak@cs.berkeley.edu

# test and clean multidelta

check:
	./testit

clean:
	rm -f *.ok *.bak file[12].txt log *.log
